### ISSUE TITLE
Cargo Media Corporate Identity

### ISSUE THREAD

**Issue by christopheschwyzer** [cargomedia/cargomedia.github.io#134]
First step is to define the value of the brand, what we did with our talk during the research day.
I attached a picture to show what we have been talking during this process

![img_8561](https://cloud.githubusercontent.com/assets/8477718/8117110/32a64e6a-1086-11e5-9b48-a55c904c075f.JPG)

Based on that we find some keywords to begin to create some visuals (the first sketches should be
available next week) representing the values we talked about. Here some examples:
- Collaboration
- Technology (playful / flexible)
- Software company
- Forward Thinking
- Personal growth
- Freedom

Please, feel free to add your inputs, such as your point of view of Cargo Media, how you see it, what are the values of the company. It would help to define and shape the new Brand.

**Comment by fabianfrey** [comment]
@seriff can you please create the shared google docs and upload the logo drafts, so that we can get input from the team?

**Comment by seriff** [comment]
I will do it, I just wanna work it a bit the logos and add a description,
to have a bit more choices!

but would it be better if I do some screen shots and upload it on the
repository?

**Comment by fabianfrey** [comment]
Best would probably be, to open a new issue only for the logo feedback, there I think you could upload the drafts.

**Comment by fabianfrey** [comment]
We are gathering values and tag lines, so everybody feel free to give your input for the CI here: https://docs.google.com/spreadsheets/d/1Sf3unk7Y8us_wYYEBRj6wZht8zBl6k8hLopaFujwtng/edit#gid=0.

**Comment by christopheschwyzer** [comment]
Some inspiration for tag lines: http://www.advergize.com/branding/120-list-of-slogans-from-information-technology-companies/

**Comment by seriff** [comment]
So far we had 18 people taking part at the vote on the doodle!
and at the moment the top 3 are "International" with 12 votes, then "flexibility" with 9 votes and the tired its "Technology" with 8 votes!

**Comment by fabianfrey** [comment]
Ok great. Two others that got quite a lot of votes are "cutting edge" and "open source". Let's discuss the results next week.

**Comment by gregdumas** [comment]
Since we can't use the tag line "social democracy" I suggest using something like *Collaborative Technology* or *Moving Forward* or something like that.  Does it have to be one word? I don't think one word says enough.

**Comment by seriff** [comment]
Hey guys,

I've been doing some research about the icon (animals) and I was wondering what was the best direction. thats one of the reason Im posting this comment now.

As you know I started to create some of the animals icon (using just lines), here some examples:

<img width="195" alt="screen shot 2015-09-09 at 4 15 13 pm" src="https://cloud.githubusercontent.com/assets/8477718/9764185/0024362c-570e-11e5-85b0-cb6b1c00c88e.png">

<img width="193" alt="screen shot 2015-09-09 at 4 15 17 pm" src="https://cloud.githubusercontent.com/assets/8477718/9764186/03c36b54-570e-11e5-99d9-64fd8bff32df.png">

The other solutions would be to go with something in bitmap / pixel art, here some of the examples I thought we could be good:

![movemberdribbble](https://cloud.githubusercontent.com/assets/8477718/9764216/2a462294-570e-11e5-929e-693e2342d7c7.png)

![ramsesdribble](https://cloud.githubusercontent.com/assets/8477718/9764223/2f619628-570e-11e5-808a-63b93a352e84.png)

![stormtrooperanimated_dribbble2](https://cloud.githubusercontent.com/assets/8477718/9764228/3300225e-570e-11e5-998c-8c61e1e66645.gif)

![tumblr_msfet080sj1scov85o1_250](https://cloud.githubusercontent.com/assets/8477718/9764233/38f87788-570e-11e5-958c-ca0f93197d8c.gif)

your feedback would be very appreciated!

Cheers

**Comment by fabianfrey** [comment]
I would definitely go, with some pixel art. Not sure though, if it should be animated or not and if should be portraits or something random.

**Comment by njam** [comment]
I would also go with the pixel art, mainly because I think it will give the avatars more *character*.

**Comment by seriff** [comment]
Hej, here the PDF with the drafts for the website.

[cargomedia_test.pdf](https://github.com/cargomedia/cargomedia.github.io/files/8549/cargomedia_test.pdf)

**Comment by fabianfrey** [comment]
I like 3, 8, 11, 12 and 16! What do you guys think? cc @christopheschwyzer @njam @NicolasSchmutz

**Comment by NicolasSchmutz** [comment]
very cool stuff! I like: 3, 5, 9, 12, 16
