### ISSUE TITLE
Cargo Media Logo

### ISSUE THREAD

**Issue by seriff** [cargomedia/cargomedia.github.io#135]
Hey guys,

Here some research I've been working on, I decided to stay in B/W to concentrate on the meaning of the shapes of the symbol and to be sure it would respect the values we defined during our talks.

here the link to see the different options, there is 3 diferents folders:

https://drive.google.com/open?id=0B9dhnwV6j5TJVDNGMlRWellzTTQ&authuser=0

here the description:

Folder 1

The idea with those different symbol is to combine the “C” of Cargo & the “M” of Media to create a unique wordmark. The symbol use the first letters of the name and add the values such as “sharing”, “connect” by crossing the strokes to each other, it also give some depth (see the example 1.)

Folder 2

This second routes, its more about connection, sharing, social. the dots can be represented as people. those dots are connected to each other in some examples (4, 6). Sometimes there no strokes to connect them, but they are still pretty close to each other.

Folder 3

Last exploration was more about choosing different routes, such as the expansion (ex.8) and the complete opposite for the example 9. We still keep the value of sharing, proximity,  technology, etc…

**Comment by ppp0** [comment]
Wow, you're not making decisions easy! They all look great.. 
Personally I favour 2.7

**Comment by njam** [comment]
I prefer if all letters have the same height - looks more techy :) Especially great in 3.10 (upper case)!
I like the graphics of 3.9 the most.

**Comment by fabianfrey** [comment]
I like 1., 3., 9. and 11. Imo nr 1. has a great symbolic meaning, the box that is being built.  Generally I agree, all letters the same height looks good. I am not sure, if we should have a space between cargo and media.

**Comment by christopheschwyzer** [comment]
I like where _8_ &  _9_ are heading.
I like font _2_, _9_, _10_

**Comment by vogdb** [comment]
I like all and can not pick anything.

**Comment by NicolasSchmutz** [comment]
I like symbol 1 and 11 and agree with @fabianfrey on symbolic meaning from 1.
I like font 2, 4, 7, 11 (the simple ones without much curlicue)

**Comment by dlondero** [comment]
I like 9 and 10!

**Comment by kris-lab** [comment]
- I like 4, 10, 11
- I like font 4 ,7, 11

**Comment by eillasti** [comment]
I like 4, it reminds me scifi and space travel :). Also 2, 3 and 11 are nice.

**Comment by gregdumas** [comment]
my choice is folder 3, #9

why did we need a new logo?  I actually like the current one.

**Comment by fvovan** [comment]
I like  #11, #5  but #1 and #10 are not bad too,
They are quite simple to be reproduced and recognized.

**Comment by mariansollmann** [comment]
Logo 9
Font 10

**Comment by seriff** [comment]
Ok, here a final test I made who looks good, more will be upload as soon as I find the way to animate it!
Cheers

![cargomedia_logo_test1](https://cloud.githubusercontent.com/assets/8477718/8460496/56d8dee8-2025-11e5-8e81-66c28c2b9baf.gif)

**Comment by seriff** [comment]
We even imagine it with a variation of colors, it could look pretty nice

**Comment by christopheschwyzer** [comment]
I like the idea of having a logo with an animation. 
To consider
- Shouldn't be endless - for most use cases, we still need a static logo. 
- Animation should be more of an additional effect, e.g. when you load up the web site, at the beginning / end of a clip etc.

Of course the _in motion_ theme can be incorporated in other static designs. Some inspiration http://brandcenter.swisscom.com/de-DE/Public/Marke/Corporate-Identity (I'm not a huge fan of it, but it's definitely thought through, and the logo's characteristics are applied to all designs / products.)

**Comment by Unquenchable** [comment]
I like 3 and 9. :)

**Comment by seriff** [comment]
Construction of the logo, we are getting there! :)

<img width="856" alt="screen shot 2015-09-14 at 3 58 45 pm" src="https://cloud.githubusercontent.com/assets/8477718/9851574/a7a5c17e-5af9-11e5-9b02-1ff60b3d728c.png">

**Comment by fabianfrey** [comment]
:sunglasses:
