### ISSUE TITLE
Use Prismic.io CMS

### ISSUE THREAD

**Issue by njam** [cargomedia/cargomedia.github.io#164]
Account: https://cargomediach.prismic.io/ (see LastPass)

Reference implementation (renee.ch):
https://github.com/njam/renee-bar.github.io/tree/prismic

Prismic JS SDK:
Code: https://github.com/prismicio/javascript-kit
Docu: http://prismicio.github.io/javascript-kit/

Goal: load team members and intro texts from CMS. Can be extended later.

**Comment by christopheschwyzer** [comment]
@njam just out of curiosity - did you compare _prisimic.io_ with other similar products like http://osmek.com/ or https://www.contentful.com - any reason for one over the other?

**Comment by njam** [comment]
I checked a few similar products, including Contentful. Haven't seen Osmek.
I didn't evaluate them deeply. Just tried to find out how to create a list of events (for Renée), and query them with a date constraint. Seemed easiest with Prismic.
