### ISSUE TITLE
Serve prismic files statically 

### ISSUE THREAD

**Issue by christopheschwyzer** [cargomedia/cargomedia.github.io#167]
Use `baked.js`: https://github.com/prismicio/baked.js

Tutorial: https://prismic.io/blog/bakedjs-integrate-content-management-into-a-static-website-generator-using-javascript

**Comment by njam** [comment]
https://youtrack.cargomedia.ch/issue/FB-244

**Comment by christopheschwyzer** [comment]
oh of course
